version: '3.8'

volumes:
    app_data:
    postgres_data:

    
services:
  app:
    build: .
    image: blog
    container_name: blog_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - app_data:/app_data
  postgres:
    image: postgres
    container_name: database_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data